image: docker

services:
    - docker:dind
    
stages:
    - build
    - test
    - deploy

build:
    stage: build
    only:
        - develop
        - master
    script:
        - pwd
        - ls ~/
        - echo building...
        - ./gradlew clean build

test:
    stage: test
    only:
        - develop
        - master
    script:
        - echo testing...
        - ./gradlew test

deploy:
    stage: deploy
    only:
        - master
    script:
        - ./scripts/build.sh
        - docker-compose up -d --remove-orphans