spring:
  application:
    name: MainService
  thymeleaf:
    check-template: false
    check-template-location: false

logging:
  level:
    com:
      netflix:
        config:
          sources:
            URLConfigurationSource: ERROR
---
spring:
  profiles:
    active: dev

  boot:
    admin:
      client:
        url: [http://localhost:1111]
        auto-registration: true
        username: admin
        password: admin
        instance:
          prefer-ip: true

management:
  server:
    port: 8080
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

database:
  host: localhost
  port: 8529
  protocol: http
  dbName: default-database
  mountPath: database-service

---
spring:
  profiles:
    active: docker
  thymeleaf:
    enabled: false
  boot:
    admin:
      client:
        url: [http://admin:1111]
        auto-registration: true
        username: admin
        password: admin
        instance:
          prefer-ip: true

management:
  server:
    port: 8080
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: logs/spring-boot-logger.log

database:
  host: database-service
  port: 8529
  protocol: http
  dbName: default-database
  mountPath: database-service

---

spring:
  profiles:
    active: test